name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Upgrade pip
        run: python -m pip install -U pip
      - name: Install deps (tests)
        run: pip install -e '.[test]'
      - name: (Optional) Install agent extras
        run: |
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            pip install -e '.[agent]'
          fi
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest -q
